name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image
        run: |
          IMAGE_URI=your_account_id.dkr.ecr.us-east-1.amazonaws.com/vibe-api
          docker build -t vibe-api .
          docker tag vibe-api:latest $IMAGE_URI:latest
          docker push $IMAGE_URI:latest

      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster vibe-cluster \
            --service vibe-service \
            --force-new-deployment
